apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  scrape_configs.yaml: |
    - job_name: 'argocd'
      metrics_path: /metrics
      static_configs:
        - targets: ['argocd-server.argocd.svc.cluster.local:8082']

