apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  server:
    cors:
      enabled: true
      allowedOrigins: '*'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  scrape_configs.yaml: |
    - job_name: 'argocd'
      metrics_path: /metrics
      static_configs:
        - targets: ['argocd-server.argocd.svc.cluster.local:8082']
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: latest
    helm:
      valueFiles:
        - values-prometheus.yaml
  project: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: latest
    helm:
      valueFiles:
        - values-argocd.yaml
  project: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  destination:
    namespace: victoria-metrics
    server: https://kubernetes.default.svc
  source:
    chart: victoria-metrics
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: latest
    helm:
      valueFiles:
        - values-victoria.yaml
  project: default

