name: Release Helm Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.5.4'

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
          echo "${{ secrets.K8S_TOKEN }}" | base64 --decode > ~/.kube/token
          kubectl config set-credentials github-actions --token=$(cat ~/.kube/token)
          kubectl config set-context github-actions --cluster=minikube --user=github-actions --namespace=default
          kubectl config use-context github-actions
          kubectl config view # Verificar el archivo kubeconfig

      - name: Helm upgrade kube-prometheus-stack
        run: |
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring -f values-prometheus.yaml
        env:
          KUBECONFIG: ~/.kube/config

      - name: Helm upgrade victoria-metrics
        run: |
          helm upgrade --install victoria-metrics victoriametrics/victoria-metrics-cluster --namespace victoria-metrics -f values-victoria.yaml
        env:
          KUBECONFIG: ~/.kube/config

      - name: Helm upgrade argo-cd
        run: |
          helm upgrade --install argo-cd argo/argo-cd --namespace argocd -f values-argocd.yaml
        env:
          KUBECONFIG: ~/.kube/config

